//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoOrientacao.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public int IdPessoa { get; set; }
        public int IdUsuario { get; set; }
        public string Nome { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
